organizations: # 这个网络中的参与组织
  Org1:
    users:
      BuiltInAlice:
        phrase: "//Alice"
        address: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
  Org2:
    users:
      BuiltInBob:
        phrase: "//Bob"
        address: "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty"
chaincodes:
  universalCc:
    address: "5DFjoJonDNw4i5Y4KbrSDtRk9tjWwXM63Qob5Ne2EYhU6Z8w"
    abiPath: "blbc/metadata.json"
apiPrefix: "http://localhost:8080"
