organizations: # 这个网络中的参与组织
  Org1:
    users:
      BuiltInAlice:
        address: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
chaincodes:
  universalCc:
    address: "5GCgpEr5yp2A8DjZJVR1eGLCvDUTpJnYsR2iz3sWBpKEperH"
    abiPath: "blbc/metadata.json"
apiPrefix: "http://localhost:8080"
